# Generated by Django 6.0.3 on 2026-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs', models.IntegerField()),
                ('emf', models.IntegerField()),
                ('vlsi', models.IntegerField()),
                ('trlf', models.IntegerField()),
            ],
        ),
    ]
