# Generated by Django 6.0.3 on 2026-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('hosuing_loan', models.CharField(max_length=50)),
                ('personal_loan', models.CharField(max_length=50)),
                ('camping', models.IntegerField()),
                ('poutcomes', models.IntegerField()),
            ],
        ),
    ]
