# Generated by Django 6.0.3 on 2026-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_age', models.IntegerField()),
                ('s_dept', models.CharField(max_length=50)),
                ('s_reg', models.IntegerField()),
                ('s_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs', models.IntegerField()),
                ('emf', models.IntegerField()),
                ('vlsi', models.IntegerField()),
                ('trlf', models.IntegerField()),
            ],
        ),
    ]
